[package]
name = "ebpf-verifier-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
cxx = { version = "1.0.58", default-features = false, features = ["alloc"] }

[build-dependencies]
cxx-build = "1.0.58"
